#!/bin/bash

set -e

# Load .env file if it exists
SCRIPT_DIR="$(dirname "$0")"
if [ -f "$SCRIPT_DIR/../.env" ]; then
    set -a
    source "$SCRIPT_DIR/../.env"
    set +a
fi

DB_TYPE=${DB_TYPE:-mysql}
PRISMA_DIR="$(dirname "$0")/../prisma"

if [[ "$DB_TYPE" != "mysql" && "$DB_TYPE" != "postgresql" ]]; then
    echo "Error: DB_TYPE must be 'mysql' or 'postgresql'"
    exit 1
fi

# Build DB_CONNECTION_STRING if not set
if [[ -z "$DB_CONNECTION_STRING" ]]; then
    case "$DB_TYPE" in
        postgresql)
            DB_CONNECTION_STRING="postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
            ;;
        mysql)
            DB_CONNECTION_STRING="mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
            ;;
    esac
    # Export for subsequent commands and update .env
    export DB_CONNECTION_STRING
    if [ -f "$SCRIPT_DIR/../.env" ]; then
        if grep -q "^DB_CONNECTION_STRING=" "$SCRIPT_DIR/../.env"; then
            sed -i.bak "s|^DB_CONNECTION_STRING=.*|DB_CONNECTION_STRING=\"${DB_CONNECTION_STRING}\"|" "$SCRIPT_DIR/../.env"
        else
            echo "DB_CONNECTION_STRING=\"${DB_CONNECTION_STRING}\"" >> "$SCRIPT_DIR/../.env"
        fi
        rm -f "$SCRIPT_DIR/../.env.bak"
    fi
    echo "✓ Built DB_CONNECTION_STRING from DB_* fields"
fi

echo "Setting up database for: $DB_TYPE"

cp "$PRISMA_DIR/schema.${DB_TYPE}.prisma.example" "$PRISMA_DIR/schema.prisma"
echo "✓ Copied schema.${DB_TYPE}.prisma.example to schema.prisma"

MIGRATION_NAME="20250618204012_init_janus"
TARGET_DIR="$PRISMA_DIR/migrations/$MIGRATION_NAME"
SOURCE_DIR="$PRISMA_DIR/migrations-source/${DB_TYPE}/$MIGRATION_NAME"

mkdir -p "$TARGET_DIR"
cp "$SOURCE_DIR/migration.sql" "$TARGET_DIR/migration.sql"
echo "✓ Copied ${DB_TYPE} migrations"

LOCK_FILE="$PRISMA_DIR/migrations/migration_lock.toml"
cat > "$LOCK_FILE" << EOF
# Please do not edit this file manually
# It should be added in your version-control system (e.g. Git)
provider = "${DB_TYPE}"
EOF
echo "✓ Updated migration_lock.toml for ${DB_TYPE}"

echo ""
echo "Database setup complete for $DB_TYPE!"
echo ""
echo "Next steps:"
echo "  1. Configure your .env file with database credentials"
echo "  2. Run: npx prisma generate"
echo "  3. Run: npx prisma migrate resolve --applied 0_init"
echo "  4. Run: npx prisma migrate deploy"
